//==============================================================================
// I2C Master (Standard-mode 100 kHz), single-byte transaction
// - Supports: 1-byte WRITE (master->slave) and 1-byte READ (slave->master)
// - SDA is open-drain: drive low or release (Z), pull-up is external
// - SCL is generated by master (no clock stretching support in this учебна версія)
// - start_cmd can be a short pulse: request is latched when master is idle
//
// Transaction format:
//   START
//   Address(7) + R/W(1)
//   ACK from slave
//   If WRITE: Data byte -> ACK from slave -> STOP
//   If READ : Data byte <- NACK from master -> STOP
//==============================================================================

module i2c_master #(
    parameter integer CLK_HZ = 50_000_000,
    parameter integer I2C_HZ = 100_000
)(
    input  wire       clk,
    input  wire       rst_n,
    input  wire       start_cmd,
    input  wire [6:0] slave_addr,
    input  wire       rw_bit,       // 0=write, 1=read
    input  wire [7:0] data_in,      // data to write (used when rw_bit=0)
    output reg  [7:0] data_out,     // data read (valid when rw_bit=1 and done=1)
    output reg        busy,
    output reg        scl,
    inout  wire       sda,
    output reg        done
);

    //--------------------------------------------------------------------------
    // I2C timebase: half-period tick (SCL changes on each tick)
    // DIV_HALF = CLK_HZ / (2*I2C_HZ)
    //--------------------------------------------------------------------------
    localparam integer DIV_HALF = (CLK_HZ / (2*I2C_HZ));
    reg [31:0] div_cnt;
    wire i2c_tick = (div_cnt == (DIV_HALF-1));

    //--------------------------------------------------------------------------
    // Open-drain SDA control
    // sda_oe=1 drives SDA low, sda_oe=0 releases line (Z) so pull-up makes it high
    //--------------------------------------------------------------------------
    reg  sda_oe;
    wire sda_in = sda;
    assign sda = sda_oe ? 1'b0 : 1'bz;

    //--------------------------------------------------------------------------
    // Latched command (so start_cmd pulse can be short)
    //--------------------------------------------------------------------------
    reg        start_pending;
    reg [6:0]  lat_addr;
    reg        lat_rw;
    reg [7:0]  lat_data;

    //--------------------------------------------------------------------------
    // FSM: each state lasts one half-period (advances only on i2c_tick)
    // - “*_LOW” states: SCL=0, SDA may change
    // - “*_HIGH” states: SCL=1, SDA must be stable, sampling happens here
    //--------------------------------------------------------------------------
    localparam [4:0]
        ST_IDLE          = 5'd0,
        ST_START         = 5'd1,

        ST_ADDR_LOW      = 5'd2,
        ST_ADDR_HIGH     = 5'd3,
        ST_ADDR_ACK_LOW  = 5'd4,
        ST_ADDR_ACK_HIGH = 5'd5,

        ST_WDATA_LOW      = 5'd6,
        ST_WDATA_HIGH     = 5'd7,
        ST_WACK_LOW       = 5'd8,
        ST_WACK_HIGH      = 5'd9,

        ST_RDATA_LOW      = 5'd10,
        ST_RDATA_HIGH     = 5'd11,
        ST_RNACK_LOW      = 5'd12,
        ST_RNACK_HIGH     = 5'd13,

        ST_STOP_0        = 5'd14,
        ST_STOP_1        = 5'd15;

    reg [4:0] state;
    reg [3:0] bit_cnt;
    reg [7:0] shreg;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            div_cnt       <= 32'd0;

            scl           <= 1'b1;
            sda_oe        <= 1'b0;

            busy          <= 1'b0;
            done          <= 1'b0;
            data_out      <= 8'd0;

            start_pending <= 1'b0;
            lat_addr      <= 7'd0;
            lat_rw        <= 1'b0;
            lat_data      <= 8'd0;

            state         <= ST_IDLE;
            bit_cnt       <= 4'd0;
            shreg         <= 8'd0;
        end else begin
            // timebase
            if (i2c_tick) div_cnt <= 32'd0;
            else          div_cnt <= div_cnt + 32'd1;

            // one-cycle “done” pulse
            done <= 1'b0;

            // latch new request when idle
            if (!busy && start_cmd) begin
                start_pending <= 1'b1;
                lat_addr      <= slave_addr;
                lat_rw        <= rw_bit;
                lat_data      <= data_in;
            end

            if (i2c_tick) begin
                case (state)
                    ST_IDLE: begin
                        scl    <= 1'b1;
                        sda_oe <= 1'b0;
                        busy   <= 1'b0;

                        if (start_pending) begin
                            start_pending <= 1'b0;
                            busy          <= 1'b1;

                            // Address byte: {7-bit addr, R/W}
                            shreg   <= {lat_addr, lat_rw};
                            bit_cnt <= 4'd7;

                            state <= ST_START;
                        end
                    end

                    // START condition: SDA падає при SCL=1
                    ST_START: begin
                        scl    <= 1'b1;
                        sda_oe <= 1'b1;   // pull SDA low
                        state  <= ST_ADDR_LOW;
                    end

                    // Shift out address bits (SDA changes when SCL=0)
                    ST_ADDR_LOW: begin
                        scl    <= 1'b0;
                        sda_oe <= (shreg[7] == 1'b0);  // 0 -> drive low, 1 -> release
                        state  <= ST_ADDR_HIGH;
                    end

                    // Hold on SCL=1, then shift
                    ST_ADDR_HIGH: begin
                        scl   <= 1'b1;
                        shreg <= {shreg[6:0], 1'b0};

                        if (bit_cnt == 0) state <= ST_ADDR_ACK_LOW;
                        else begin
                            bit_cnt <= bit_cnt - 1'b1;
                            state   <= ST_ADDR_LOW;
                        end
                    end

                    // ACK bit: master releases SDA
                    ST_ADDR_ACK_LOW: begin
                        scl    <= 1'b0;
                        sda_oe <= 1'b0;
                        state  <= ST_ADDR_ACK_HIGH;
                    end

                    // Sample ACK on SCL=1
                    ST_ADDR_ACK_HIGH: begin
                        scl <= 1'b1;

                        if (sda_in == 1'b0) begin
                            if (lat_rw == 1'b0) begin
                                shreg   <= lat_data;
                                bit_cnt <= 4'd7;
                                state   <= ST_WDATA_LOW;
                            end else begin
                                shreg   <= 8'd0;
                                bit_cnt <= 4'd7;
                                state   <= ST_RDATA_LOW;
                            end
                        end else begin
                            state <= ST_STOP_0; // NACK -> stop
                        end
                    end

                    // WRITE data byte
                    ST_WDATA_LOW: begin
                        scl    <= 1'b0;
                        sda_oe <= (shreg[7] == 1'b0);
                        state  <= ST_WDATA_HIGH;
                    end

                    ST_WDATA_HIGH: begin
                        scl   <= 1'b1;
                        shreg <= {shreg[6:0], 1'b0};

                        if (bit_cnt == 0) state <= ST_WACK_LOW;
                        else begin
                            bit_cnt <= bit_cnt - 1'b1;
                            state   <= ST_WDATA_LOW;
                        end
                    end

                    // Slave ACK after write byte (master releases SDA)
                    ST_WACK_LOW: begin
                        scl    <= 1'b0;
                        sda_oe <= 1'b0;
                        state  <= ST_WACK_HIGH;
                    end

                    ST_WACK_HIGH: begin
                        scl   <= 1'b1;
                        state <= ST_STOP_0;
                    end

                    // READ data byte: master releases SDA, slave drives bits
                    ST_RDATA_LOW: begin
                        scl    <= 1'b0;
                        sda_oe <= 1'b0;
                        state  <= ST_RDATA_HIGH;
                    end

                    // Sample data bit on SCL=1
                    ST_RDATA_HIGH: begin
                        scl   <= 1'b1;
                        shreg <= {shreg[6:0], sda_in};

                        if (bit_cnt == 0) state <= ST_RNACK_LOW;
                        else begin
                            bit_cnt <= bit_cnt - 1'b1;
                            state   <= ST_RDATA_LOW;
                        end
                    end

                    // NACK for single-byte read: master leaves SDA released (high by pull-up)
                    ST_RNACK_LOW: begin
                        scl    <= 1'b0;
                        sda_oe <= 1'b0;
                        state  <= ST_RNACK_HIGH;
                    end

                    ST_RNACK_HIGH: begin
                        scl      <= 1'b1;
                        data_out <= shreg;
                        state    <= ST_STOP_0;
                    end

                    // STOP sequence: SCL low, SDA low; then SCL high and SDA release
                    ST_STOP_0: begin
                        scl    <= 1'b0;
                        sda_oe <= 1'b1;
                        state  <= ST_STOP_1;
                    end

                    ST_STOP_1: begin
                        scl    <= 1'b1;
                        sda_oe <= 1'b0;

                        busy   <= 1'b0;
                        done   <= 1'b1;
                        state  <= ST_IDLE;
                    end

                    default: state <= ST_IDLE;
                endcase
            end
        end
    end

endmodule
